# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    nbResults: 8
    prefix: '%env(APP_ENV)%_'
    indices:
        - name: events
          class: App\Entity\Event
          enable_serializer_groups: true
