fos_ck_editor:
  configs:
    my_config:
      toolbar: [ [ 'Bold','Italic','Underline','Strike' ], [ 'NumberedList','BulletedList''-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ], [ 'Link','Unlink' ], [ 'pbckcode', 'Table' ], '/',  [ 'RemoveFormat' ], [ 'Maximize' ] ]
    comment:
      toolbar: [ [ 'Bold','Italic','Underline','Strike' ] ]
