vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /public/uploads/avatar
            upload_destination: '%kernel.project_dir%/public/uploads/avatar'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        event:
            uri_prefix: /public/uploads/event
            upload_destination: '%kernel.project_dir%/public/uploads/event'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true